version: '3.8'

services:
  todo_app:
    image: ghcr.io/trak2026z/todo-example-app:latest
    networks:
      - todo_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.todo_app.rule=Host(`62.93.61.19`) || Host(`localhost`)'
      - 'traefik.http.services.todo_app.loadbalancer.server.port=3000'
      - 'traefik.http.services.todo_app.loadbalancer.server.scheme=http'
      - 'traefik.http.services.todo_app.loadbalancer.passhostheader=true'

  traefik:
    image: traefik:v2.10
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - todo_net

networks:
  todo_net:
    driver: overlay